name: Ahao Common Utils CI

on: [push, pull_request]

strategy:
  matrix:
    os: [ubuntu-latest, windows-latest, macOS-latest]
    
jobs:
  job-window:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up JDK 1.8
        uses: actions/setup-java@master
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn clear package
